name: job_scout
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'
  
dependencies:

  flutter_signin_button: ^2.0.0
  firebase_auth: ^4.8.0
   
  firebase_core: ^2.15.1
  google_sign_in: ^6.1.4
   
  flutter:
    sdk: flutter
  
  image_picker: ^1.0.2
    
     

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_svg:
  

flutter:
  uses-material-design: true
  assets:
  - assets/images/


