name: job_scout
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'
  
dependencies:
  firebase_auth: ^4.10.1
  flutter_signin_button: ^2.0.0
  flutter_chat_types: ^3.6.2
  file_picker: ^5.5.0
  http: '>=0.13.6 <2.0.0'
 
  mime: ^1.0.4
  open_filex: ^4.3.2
  path_provider: ^2.0.15
  uuid: ^3.0.7
  flutter_chat_ui: ^1.6.9
  firebase_core: ^2.15.1
  google_sign_in: ^6.1.4
  intl: ^0.18.0
  url_launcher: ^6.0.10
  video_player: ^2.2.5
  cached_network_image: ^3.2.0
    
  flutter:
    sdk: flutter
  
  image_picker: ^1.0.4
  firebase_storage: ^11.5.2
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  lottie: ^2.6.0
  curved_navigation_bar: ^1.0.3
  cloud_firestore: ^4.9.1
  get: ^4.6.5
  get_storage: ^2.1.1
  dash_chat_2: ^0.0.18
  syncfusion_flutter_pdfviewer: ^23.1.39
  easy_pdf_viewer: ^1.0.7
  upi_india: ^3.0.1
  
    
     

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/images/logo_1.png"

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/animations/


