name: job_scout
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'
  
dependencies:

  flutter_signin_button: ^2.0.0
  firebase_auth: ^4.8.0
   
  firebase_core: ^2.15.1
  google_sign_in: ^6.1.4
   
  flutter:
    sdk: flutter
  
  image_picker: ^1.0.2
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  lottie: ^2.6.0
  curved_navigation_bar: ^1.0.3
  cloud_firestore: ^4.9.1
  get: ^4.6.5
  get_storage: ^2.1.1
    
     

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/images/logo_1.png"

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/animations/


