// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwViQ65_Bm8lokAH5kqzHeo6457FJkh6s',
    appId: '1:1091407447247:web:6c58ab8bcea2322466e3ba',
    messagingSenderId: '1091407447247',
    projectId: 'job-scout-73434',
    authDomain: 'job-scout-73434.firebaseapp.com',
    storageBucket: 'job-scout-73434.appspot.com',
    measurementId: 'G-TW8REXFJ5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHkLAzPShBa3XRDDR4K-rPYIbMcO8Z_0E',
    appId: '1:1091407447247:android:abc9d4d54df0f22f66e3ba',
    messagingSenderId: '1091407447247',
    projectId: 'job-scout-73434',
    storageBucket: 'job-scout-73434.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbdAft5lxTZ4OsSjOryTu8fn4PxuB1Fr0',
    appId: '1:1091407447247:ios:8d279dbec58576dd66e3ba',
    messagingSenderId: '1091407447247',
    projectId: 'job-scout-73434',
    storageBucket: 'job-scout-73434.appspot.com',
    iosClientId: '1091407447247-ljskco4k32a9e3g513g9e0bf6i47r9uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobScout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbdAft5lxTZ4OsSjOryTu8fn4PxuB1Fr0',
    appId: '1:1091407447247:ios:b7112937548eadfc66e3ba',
    messagingSenderId: '1091407447247',
    projectId: 'job-scout-73434',
    storageBucket: 'job-scout-73434.appspot.com',
    iosClientId: '1091407447247-b2bahqlfst7b2hhogkit9qjoigmp59hb.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobScout.RunnerTests',
  );
}
